### ISSUE TITLE
POSTGRES_* cannot be changed

### ISSUE THREAD

**Issue by sesceu** [hackmdio/docker-hackmd#16] opened 2017-05-12 13:27 UTC
Since hackmd/.sequelizerc contains a hard coded url to the postgres database, you cannot change the content of any POSTGRES_* variable, nor the hostname of the database server itself. If somebody wanted to use another postgres instance or change the username, table, or password, he cannot do so at the moment.

**Comment by SISheogorath** [comment] 2017-05-12 13:34
Yes, known problem, it's fixed with #14.

The problem is the migration/initialization step [here](https://github.com/hackmdio/docker-hackmd/blob/master/hackmd/.sequelizerc). If you want to change it, you have to rebuild the image.

**Comment by sesceu** [comment] 2017-05-13 19:50
Thanks, what's keeping the PR from being merged, Travis-CI issues?

**Comment by almereyda** [comment] 2017-05-14 20:39
The image is also tightly coupled with an assumption under which name the database is linked by [the Dockerfile's `CMD` directive](https://github.com/hackmdio/docker-hackmd/blob/master/hackmd/Dockerfile#L38).

**Comment by SISheogorath** [comment] 2017-05-14 22:37
This is also fixed here: https://github.com/hackmdio/docker-hackmd/pull/14/files#diff-60713fb19f6c50a2473835df63ff17f9R14

> Thanks, what's keeping the PR from being merged, Travis-CI issues?

Missing reviews. As the https://github.com/hackmdio/hackmd main repo is in a big refactor process there is currently a bottleneck in the programmer resources. And as docker image is currently a "Nice-to-have" priorities are not high. Possibly the pull request becomes part of the main repository in the next weeks.

@jackycute knows all the details.

**Comment by almereyda** [comment] 2017-05-15 10:16
Are we talking about this https://github.com/hackmdio/hackmd/projects/1 ? Then at least we know the priorities and see where we can help out.

**Comment by jackycute** [comment] 2017-05-15 15:16
Actually we need help to review and test of the PR #14 
Our main repo is under refactoring but we'll try not affect docker build.

**Comment by TheAssassin** [comment] 2017-10-15 15:08
This could be quick-fixed with dockerize's template feature by the way. By rendering `config.json` with the environment variables from a template, this could be implemented with little effort, while not affecting anything in #14. Would you accept such a fix?

**Comment by SISheogorath** [comment] 2017-10-28 01:31
We just merged #14 should be fixed now.

**Closed by SISheogorath** 2017-10-28 01:31 UTC
Labels: bug
