### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by DevTown** [hackmdio/docker-hackmd#31] opened 2018-01-18 17:13 UTC
When I try to install die 1.0.0-ce version I got some errors when the app starts:

 docker-compose up
Creating dockerhackmd_app_1      ... done
Creating dockerhackmd_database_1 ... done
Attaching to dockerhackmd_database_1, dockerhackmd_app_1
database_1  | LOG:  database system was shut down at 2018-01-02 22:48:41 UTC
database_1  | LOG:  MultiXact member wraparound protections are now enabled
database_1  | LOG:  database system is ready to accept connections
database_1  | LOG:  autovacuum launcher started
database_1  | LOG:  incomplete startup packet
app_1       | postgres://hackmd:hackmdpass@hackmdPostgres:5432/hackmd
app_1       | hackmdPostgres:5432
app_1       | 2018/01/18 16:59:00 Waiting for host: hackmdPostgres:5432
app_1       | 2018/01/18 16:59:00 Connected to tcp://hackmdPostgres:5432
app_1       | 
app_1       | Sequelize [Node: 6.12.3, CLI: 2.8.0, ORM: 3.30.4]
app_1       | 
app_1       | Parsed url postgres://hackmd:*****@hackmdPostgres:5432/hackmd
app_1       | (node:20) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | == 20150702001020-update-to-0_3_1: migrating =======
database_1  | ERROR:  column "shortid" of relation "Notes" already exists
database_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT '0000000000';
app_1       | { SequelizeDatabaseError: column "shortid" of relation "Notes" already exists
app_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
app_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Result.emit (events.js:188:7)
app_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)
app_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Connection.emit (events.js:188:7)
app_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Socket.emit (events.js:188:7)
app_1       |     at readableAddChunk (_stream_readable.js:176:18)
app_1       |     at Socket.Readable.push (_stream_readable.js:134:10)
app_1       |     at TCP.onread (net.js:547:20)
app_1       |   name: 'SequelizeDatabaseError',
app_1       |   message: 'column "shortid" of relation "Notes" already exists',
app_1       |   parent: 
app_1       |    { error: column "shortid" of relation "Notes" already exists
app_1       |        at Connection.parseE (/hackmd/node_modules/pg/lib/connection.js:567:11)
app_1       |        at Connection.parseMessage (/hackmd/node_modules/pg/lib/connection.js:391:17)
app_1       |        at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:129:22)
app_1       |        at emitOne (events.js:96:13)
app_1       |        at Socket.emit (events.js:188:7)
app_1       |        at readableAddChunk (_stream_readable.js:176:18)
app_1       |        at Socket.Readable.push (_stream_readable.js:134:10)
app_1       |        at TCP.onread (net.js:547:20)
app_1       |      name: 'error',
app_1       |      length: 131,
app_1       |      severity: 'ERROR',
app_1       |      code: '42701',
app_1       |      detail: undefined,
app_1       |      hint: undefined,
app_1       |      position: undefined,
app_1       |      internalPosition: undefined,
app_1       |      internalQuery: undefined,
app_1       |      where: undefined,
app_1       |      schema: undefined,
app_1       |      table: undefined,
app_1       |      column: undefined,
app_1       |      dataType: undefined,
app_1       |      constraint: undefined,
app_1       |      file: 'tablecmds.c',
app_1       |      line: '5110',
app_1       |      routine: 'check_for_column_name_collision',
app_1       |      sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
app_1       |   original: 
app_1       |    { error: column "shortid" of relation "Notes" already exists
app_1       |        at Connection.parseE (/hackmd/node_modules/pg/lib/connection.js:567:11)
app_1       |        at Connection.parseMessage (/hackmd/node_modules/pg/lib/connection.js:391:17)
app_1       |        at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:129:22)
app_1       |        at emitOne (events.js:96:13)
app_1       |        at Socket.emit (events.js:188:7)
app_1       |        at readableAddChunk (_stream_readable.js:176:18)
app_1       |        at Socket.Readable.push (_stream_readable.js:134:10)
app_1       |        at TCP.onread (net.js:547:20)
app_1       |      name: 'error',
app_1       |      length: 131,
app_1       |      severity: 'ERROR',
app_1       |      code: '42701',
app_1       |      detail: undefined,
app_1       |      hint: undefined,
app_1       |      position: undefined,
app_1       |      internalPosition: undefined,
app_1       |      internalQuery: undefined,
app_1       |      where: undefined,
app_1       |      schema: undefined,
app_1       |      table: undefined,
app_1       |      column: undefined,
app_1       |      dataType: undefined,
app_1       |      constraint: undefined,
app_1       |      file: 'tablecmds.c',
app_1       |      line: '5110',
app_1       |      routine: 'check_for_column_name_collision',
app_1       |      sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' },
app_1       |   sql: 'ALTER TABLE "public"."Notes" ADD COLUMN "shortid" VARCHAR(255) NOT NULL DEFAULT \'0000000000\';' }
app_1       | (node:32) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | >> WARNING: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead. 
app_1       | >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'b867d45e-8983-40b1-bc99-cc8c7e33f09c' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '570b0d9e-8ce4-46bf-a21e-edd84a7d317e' ORDER BY "Revision"."createdAt" DESC;
app_1       | Unhandled rejection Error: SequelizeDatabaseError: column "authorship" does not exist
app_1       |     at /hackmd/app.js:214:22
app_1       |     at /hackmd/lib/models/revision.js:162:27
app_1       |     at /hackmd/lib/models/revision.js:219:22
app_1       |     at /hackmd/node_modules/async/dist/async.js:421:16
app_1       |     at iteratorCallback (/hackmd/node_modules/async/dist/async.js:996:13)
app_1       |     at /hackmd/node_modules/async/dist/async.js:906:16
app_1       |     at Model.<anonymous> (/hackmd/lib/models/revision.js:291:18)
app_1       |     at Model.tryCatcher (/hackmd/node_modules/bluebird/js/release/util.js:16:23)
app_1       |     at Promise._settlePromiseFromHandler (/hackmd/node_modules/bluebird/js/release/promise.js:512:31)
app_1       |     at Promise._settlePromise (/hackmd/node_modules/bluebird/js/release/promise.js:569:18)
app_1       |     at Promise._settlePromise0 (/hackmd/node_modules/bluebird/js/release/promise.js:614:10)
app_1       |     at Promise._settlePromises (/hackmd/node_modules/bluebird/js/release/promise.js:689:18)
app_1       |     at Async._drainQueue (/hackmd/node_modules/bluebird/js/release/async.js:133:16)
app_1       |     at Async._drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:143:10)
app_1       |     at Immediate.Async.drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:17:14)
app_1       |     at runCallback (timers.js:672:20)
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'dc9eb5ee-8359-4bdc-8239-e7c1de2d9d4a' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'e1ecb4d7-5c4f-4183-99ba-27ff0e6324e0' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '17a3d600-774b-4e07-879e-08aa05380335' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '772f124a-8c6e-444b-bc73-3809b1d12797' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'b867d45e-8983-40b1-bc99-cc8c7e33f09c' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '570b0d9e-8ce4-46bf-a21e-edd84a7d317e' ORDER BY "Revision"."createdAt" DESC;
app_1       | 2018-01-18T17:04:07.412Z - error: revision saver failed: SequelizeDatabaseError: column "authorship" does not exist
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'dc9eb5ee-8359-4bdc-8239-e7c1de2d9d4a' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = 'e1ecb4d7-5c4f-4183-99ba-27ff0e6324e0' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '17a3d600-774b-4e07-879e-08aa05380335' ORDER BY "Revision"."createdAt" DESC;
database_1  | ERROR:  column "authorship" does not exist at character 59
database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '772f124a-8c6e-444b-bc73-3809b1d12797' ORDER BY "Revision"."createdAt" DESC;
`

**Comment by SISheogorath** [comment] 2018-01-18 17:58
I just tried to reproduce it on Play with Docker but wasn't able to do so. Did you may restarted your container very early?

Also is it a fresh install or one with existing data?

**Comment by DevTown** [comment] 2018-01-18 18:08
It is a fresh install. I just run  git clone https://github.com/hackmdio/docker-hackmd.git 
change in the folder , edit the hackmd version from 1.0.0 to 1.0.0-ce (version 1.0.0 cant find) and then i run docker-compose up (verion 2 of docker-compose),

**Comment by DevTown** [comment] 2018-01-18 19:33
I am running 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Docker:
docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

After two times of 
``
docker-compose up -d
docker-compose down -v 
``
it seams that it works.

**Comment by SISheogorath** [comment] 2018-01-20 13:12
I agree that this is a bad first experience. But it mainly looks like the migration didn't run as it should. Which then again breaks the remaining parts.

But I don't understand why it didn't run correctly. The only possible way I can think of that creates such a situation is a restarting/crashing database or migration and then a restart on the same data.

So I'm neither sure how to reproduce and I'm still unable to do so, nor do I have any idea how to fix it.

**Comment by DevTown** [comment] 2018-01-22 21:05
Ok i tested today on a Linux Mint and it works smooth as could be. 
Is it possible that the agent starts before the DB is synced and authorship is added in the Revisions ?

**Comment by SISheogorath** [comment] 2018-01-23 09:21
I would say no, since the HackMD container (should) wait until the database is up before starting the migration and then again the real HackMD app starts after the migration.

But of course maybe there is some factor I don't see right now which makes it possible to skip one of these steps, which then again causes such a problem.

**Comment by SISheogorath** [comment] 2018-01-29 15:50
I'll close this for now. If the error appear again and we find a way to reproduce, feel free to re-open

**Closed by SISheogorath** 2018-01-29 15:50 UTC
Labels: bug, help wanted
